import massive.munit.TestSuite;

import ExampleTest;
import flash.display.BitmapDataChannelTest;
import flash.display.BitmapDataTest;
import flash.display.BitmapTest;
import flash.display.BlendModeTest;
import flash.display.CapsStyleTest;
import flash.display.DisplayObjectContainerTest;
import flash.display.DisplayObjectTest;
import flash.display.GradientTypeTest;
import flash.display.GraphicsBitmapFillTest;
import flash.display.GraphicsEndFillTest;
import flash.display.GraphicsGradientFillTest;
import flash.display.GraphicsPathCommandTest;
import flash.display.GraphicsPathTest;
import flash.display.GraphicsPathWindingTest;
import flash.display.GraphicsSolidFillTest;
import flash.display.GraphicsStrokeTest;
import flash.display.GraphicsTest;
import flash.display.InteractiveObjectTest;
import flash.display.InterpolationMethodTest;
import flash.display.JointStyleTest;
import flash.display.LineScaleModeTest;
import flash.display.LoaderInfoTest;
import flash.display.LoaderTest;
import flash.display.MovieClipTest;
import flash.display.PixelSnappingTest;
import flash.display.ShapeTest;
import flash.display.SimpleButtonTest;
import flash.display.SpreadMethodTest;
import flash.display.SpriteTest;
import flash.display.StageAlignTest;
import flash.display.StageDisplayStateTest;
import flash.display.StageQualityTest;
import flash.display.StageScaleModeTest;
import flash.display.StageTest;
import flash.display.TriangleCullingTest;
import flash.errors.ArgumentErrorTest;
import flash.errors.EOFErrorTest;
import flash.errors.ErrorTest;
import flash.errors.IllegalOperationErrorTest;
import flash.errors.RangeErrorTest;
import flash.errors.SecurityErrorTest;
import flash.errors.TypeErrorTest;
import flash.events.AccelerometerEventTest;
import flash.events.ErrorEventTest;
import flash.events.EventDispatcherTest;
import flash.events.EventPhaseTest;
import flash.events.EventTest;
import flash.events.FocusEventTest;
import flash.events.HTTPStatusEventTest;
import flash.events.IOErrorEventTest;
import flash.events.KeyboardEventTest;
import flash.events.MouseEventTest;
import flash.events.ProgressEventTest;
import flash.events.SampleDataEventTest;
import flash.events.SecurityErrorEventTest;
import flash.events.TextEventTest;
import flash.events.TimerEventTest;
import flash.events.TouchEventTest;
import flash.external.ExternalInterfaceTest;
import flash.filters.BitmapFilterTest;
import flash.filters.BitmapFilterTypeTest;
import flash.filters.BlurFilterTest;
import flash.filters.ColorMatrixFilterTest;
import flash.filters.DropShadowFilterTest;
import flash.filters.GlowFilterTest;
import flash.geom.ColorTransformTest;
import flash.geom.Matrix3DTest;
import flash.geom.MatrixTest;
import flash.geom.PointTest;
import flash.geom.RectangleTest;
import flash.geom.TransformTest;
import flash.geom.Vector3DTest;
import flash.LibTest;
import flash.media.ID3InfoTest;
import flash.media.SoundChannelTest;
import flash.media.SoundLoaderContextTest;
import flash.media.SoundTest;
import flash.media.SoundTransformTest;
import flash.MemoryTest;
import flash.net.SharedObjectFlushStatusTest;
import flash.net.SharedObjectTest;
import flash.net.URLLoaderDataFormatTest;
import flash.net.URLLoaderTest;
import flash.net.URLRequestHeaderTest;
import flash.net.URLRequestMethodTest;
import flash.net.URLRequestTest;
import flash.net.URLVariablesTest;
import flash.sensors.AccelerometerTest;
import flash.system.ApplicationDomainTest;
import flash.system.CapabilitiesTest;
import flash.system.LoaderContextTest;
import flash.system.SecurityDomainTest;
import flash.system.SystemTest;
import flash.text.AntiAliasTypeTest;
import flash.text.FontStyleTest;
import flash.text.FontTest;
import flash.text.FontTypeTest;
import flash.text.GridFitTypeTest;
import flash.text.TextFieldAutoSizeTest;
import flash.text.TextFieldTest;
import flash.text.TextFieldTypeTest;
import flash.text.TextFormatAlignTest;
import flash.text.TextFormatTest;
import flash.text.TextLineMetricsTest;
import flash.ui.KeyboardTest;
import flash.ui.MouseTest;
import flash.ui.MultitouchInputModeTest;
import flash.ui.MultitouchTest;
import flash.utils.ByteArrayTest;
import flash.utils.CompressionAlgorithmTest;
import flash.utils.EndianTest;
import flash.utils.TimerTest;
import flash.VectorTest;
import openfl.AssetsTest;
import openfl.display.DirectRendererTest;
import openfl.display.FPSTest;
import openfl.display.OpenGLViewTest;
import openfl.display.TilesheetTest;
import openfl.events.JoystickEventTest;
import openfl.events.SystemEventTest;
import openfl.gl.GLActiveInfoTest;
import openfl.gl.GLBufferTest;
import openfl.gl.GLContextAttributesTest;
import openfl.gl.GLFramebufferTest;
import openfl.gl.GLObjectTest;
import openfl.gl.GLProgramTest;
import openfl.gl.GLRenderbufferTest;
import openfl.gl.GLShaderTest;
import openfl.gl.GLTest;
import openfl.gl.GLTextureTest;
import openfl.gl.GLUniformLocationTest;
import openfl.utils.ArrayBufferTest;
import openfl.utils.ArrayBufferViewTest;
import openfl.utils.Float32ArrayTest;
import openfl.utils.Int16ArrayTest;
import openfl.utils.Int32ArrayTest;
import openfl.utils.UInt8ArrayTest;

/**
 * Auto generated Test Suite for MassiveUnit.
 * Refer to munit command line tool for more information (haxelib run munit)
 */

class TestSuite extends massive.munit.TestSuite
{		

	public function new()
	{
		super();

		add(ExampleTest);
		add(flash.display.BitmapDataChannelTest);
		add(flash.display.BitmapDataTest);
		add(flash.display.BitmapTest);
		add(flash.display.BlendModeTest);
		add(flash.display.CapsStyleTest);
		add(flash.display.DisplayObjectContainerTest);
		add(flash.display.DisplayObjectTest);
		add(flash.display.GradientTypeTest);
		add(flash.display.GraphicsBitmapFillTest);
		add(flash.display.GraphicsEndFillTest);
		add(flash.display.GraphicsGradientFillTest);
		add(flash.display.GraphicsPathCommandTest);
		add(flash.display.GraphicsPathTest);
		add(flash.display.GraphicsPathWindingTest);
		add(flash.display.GraphicsSolidFillTest);
		add(flash.display.GraphicsStrokeTest);
		add(flash.display.GraphicsTest);
		add(flash.display.InteractiveObjectTest);
		add(flash.display.InterpolationMethodTest);
		add(flash.display.JointStyleTest);
		add(flash.display.LineScaleModeTest);
		add(flash.display.LoaderInfoTest);
		add(flash.display.LoaderTest);
		add(flash.display.MovieClipTest);
		add(flash.display.PixelSnappingTest);
		add(flash.display.ShapeTest);
		add(flash.display.SimpleButtonTest);
		add(flash.display.SpreadMethodTest);
		add(flash.display.SpriteTest);
		add(flash.display.StageAlignTest);
		add(flash.display.StageDisplayStateTest);
		add(flash.display.StageQualityTest);
		add(flash.display.StageScaleModeTest);
		add(flash.display.StageTest);
		add(flash.display.TriangleCullingTest);
		add(flash.errors.ArgumentErrorTest);
		add(flash.errors.EOFErrorTest);
		add(flash.errors.ErrorTest);
		add(flash.errors.IllegalOperationErrorTest);
		add(flash.errors.RangeErrorTest);
		add(flash.errors.SecurityErrorTest);
		add(flash.errors.TypeErrorTest);
		add(flash.events.AccelerometerEventTest);
		add(flash.events.ErrorEventTest);
		add(flash.events.EventDispatcherTest);
		add(flash.events.EventPhaseTest);
		add(flash.events.EventTest);
		add(flash.events.FocusEventTest);
		add(flash.events.HTTPStatusEventTest);
		add(flash.events.IOErrorEventTest);
		add(flash.events.KeyboardEventTest);
		add(flash.events.MouseEventTest);
		add(flash.events.ProgressEventTest);
		add(flash.events.SampleDataEventTest);
		add(flash.events.SecurityErrorEventTest);
		add(flash.events.TextEventTest);
		add(flash.events.TimerEventTest);
		add(flash.events.TouchEventTest);
		add(flash.external.ExternalInterfaceTest);
		add(flash.filters.BitmapFilterTest);
		add(flash.filters.BitmapFilterTypeTest);
		add(flash.filters.BlurFilterTest);
		add(flash.filters.ColorMatrixFilterTest);
		add(flash.filters.DropShadowFilterTest);
		add(flash.filters.GlowFilterTest);
		add(flash.geom.ColorTransformTest);
		add(flash.geom.Matrix3DTest);
		add(flash.geom.MatrixTest);
		add(flash.geom.PointTest);
		add(flash.geom.RectangleTest);
		add(flash.geom.TransformTest);
		add(flash.geom.Vector3DTest);
		add(flash.LibTest);
		add(flash.media.ID3InfoTest);
		add(flash.media.SoundChannelTest);
		add(flash.media.SoundLoaderContextTest);
		add(flash.media.SoundTest);
		add(flash.media.SoundTransformTest);
		add(flash.MemoryTest);
		add(flash.net.SharedObjectFlushStatusTest);
		add(flash.net.SharedObjectTest);
		add(flash.net.URLLoaderDataFormatTest);
		add(flash.net.URLLoaderTest);
		add(flash.net.URLRequestHeaderTest);
		add(flash.net.URLRequestMethodTest);
		add(flash.net.URLRequestTest);
		add(flash.net.URLVariablesTest);
		add(flash.sensors.AccelerometerTest);
		add(flash.system.ApplicationDomainTest);
		add(flash.system.CapabilitiesTest);
		add(flash.system.LoaderContextTest);
		add(flash.system.SecurityDomainTest);
		add(flash.system.SystemTest);
		add(flash.text.AntiAliasTypeTest);
		add(flash.text.FontStyleTest);
		add(flash.text.FontTest);
		add(flash.text.FontTypeTest);
		add(flash.text.GridFitTypeTest);
		add(flash.text.TextFieldAutoSizeTest);
		add(flash.text.TextFieldTest);
		add(flash.text.TextFieldTypeTest);
		add(flash.text.TextFormatAlignTest);
		add(flash.text.TextFormatTest);
		add(flash.text.TextLineMetricsTest);
		add(flash.ui.KeyboardTest);
		add(flash.ui.MouseTest);
		add(flash.ui.MultitouchInputModeTest);
		add(flash.ui.MultitouchTest);
		add(flash.utils.ByteArrayTest);
		add(flash.utils.CompressionAlgorithmTest);
		add(flash.utils.EndianTest);
		add(flash.utils.TimerTest);
		add(flash.VectorTest);
		add(openfl.AssetsTest);
		add(openfl.display.DirectRendererTest);
		add(openfl.display.FPSTest);
		add(openfl.display.OpenGLViewTest);
		add(openfl.display.TilesheetTest);
		add(openfl.events.JoystickEventTest);
		add(openfl.events.SystemEventTest);
		add(openfl.gl.GLActiveInfoTest);
		add(openfl.gl.GLBufferTest);
		add(openfl.gl.GLContextAttributesTest);
		add(openfl.gl.GLFramebufferTest);
		add(openfl.gl.GLObjectTest);
		add(openfl.gl.GLProgramTest);
		add(openfl.gl.GLRenderbufferTest);
		add(openfl.gl.GLShaderTest);
		add(openfl.gl.GLTest);
		add(openfl.gl.GLTextureTest);
		add(openfl.gl.GLUniformLocationTest);
		add(openfl.utils.ArrayBufferTest);
		add(openfl.utils.ArrayBufferViewTest);
		add(openfl.utils.Float32ArrayTest);
		add(openfl.utils.Int16ArrayTest);
		add(openfl.utils.Int32ArrayTest);
		add(openfl.utils.UInt8ArrayTest);
	}
}
